train_dataloader:
 module: data_loaders.pt_cifar10_dataloader
 attr: get_train_dataloader
 args:
  batch_size: 64

eval_dataloader:
 module: data_loaders.pt_cifar10_dataloader
 attr: get_eval_dataloader
 args:
  batch_size: 64

model:
 module: modules.pt_cifar10_model
 attr: PtCifar10Model
 args:
  num_labels: 10

loss:
 module: torch.nn
 attr: CrossEntropyLoss

optimizer:
 module: torch.optim
 attr: SGD
 args:
  lr: 0.001
  momentum: 0.9

trainer:
 module: trainers.pt_cifar10_trainer
 attr: PtCifar10Trainer
 num_epochs: 1
 saved_model_name: pt_cifar10_model